# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 03:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('card', models.TextField()),
                ('type', models.TextField()),
                ('holder', models.TextField()),
                ('salt', models.BinaryField()),
            ],
            options={
                'db_table': 'credit_card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.TextField()),
                ('occupation', models.TextField()),
                ('licensee', models.TextField()),
                ('doing_business_as', models.TextField()),
                ('cls', models.TextField()),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zipcode', models.BigIntegerField()),
                ('county', models.TextField()),
                ('license_number', models.TextField()),
                ('primary_status', models.TextField()),
                ('secondary_status', models.TextField()),
                ('date_licensed', models.TextField()),
                ('effective_date', models.TextField()),
                ('expiration_date', models.TextField()),
                ('military', models.TextField()),
                ('alternate_license_number', models.TextField()),
            ],
            options={
                'db_table': 'license',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'newsletter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('username', models.TextField()),
                ('userid', models.TextField()),
                ('network', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WholeSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wholesale',
                'managed': True,
            },
        ),
    ]
