# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapi', '0002_auto_20170707_1357'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='creditcard',
            table='creditcard',
        ),
    ]
