# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customapi', '0004_auto_20170707_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField()),
                ('card', models.TextField()),
                ('ctype', models.TextField()),
                ('holder', models.TextField()),
                ('salt', models.BinaryField()),
            ],
            options={
                'db_table': 'user_credit_card',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
